# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:54
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('scoreboard', '0001_initial'), ('scoreboard', '0002_add_logo_field'), ('scoreboard', '0003_add_championship_rounds_match'), ('scoreboard', '0004_detailed_fields'), ('scoreboard', '0005_add_division_icon_slugs'), ('scoreboard', '0006_auto_20170816_0946'), ('scoreboard', '0007_championship_division')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='shortname')),
            ],
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoret1', models.SmallIntegerField()),
                ('trybonust1', models.BooleanField(default=False)),
                ('scoret2', models.SmallIntegerField()),
                ('trybonust2', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Championship')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='championship_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Round'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='scoreboard.Team', verbose_name='Team 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='scoreboard.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoret1',
            field=models.SmallIntegerField(default=0, verbose_name='Score Team 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoret2',
            field=models.SmallIntegerField(default=0, verbose_name='Score Team 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='trybonust1',
            field=models.BooleanField(default=False, verbose_name='Try Bonus'),
        ),
        migrations.AlterField(
            model_name='match',
            name='trybonust2',
            field=models.BooleanField(default=False, verbose_name='Try Bonus'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Division', verbose_name='Division'),
        ),
    ]
