# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='team',
            name='shortname',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
