# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_add_logo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoret1', models.SmallIntegerField()),
                ('trybonust1', models.BooleanField(default=False)),
                ('scoret2', models.SmallIntegerField()),
                ('trybonust2', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Championship')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='championship_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Round'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='scoreboard.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='scoreboard.Team'),
        ),
    ]
