# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_add_championship_rounds_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoret1',
            field=models.SmallIntegerField(default=0, verbose_name='Score Team 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoret2',
            field=models.SmallIntegerField(default=0, verbose_name='Score Team 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='scoreboard.Team', verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='trybonust1',
            field=models.BooleanField(default=False, verbose_name='Try Bonus'),
        ),
        migrations.AlterField(
            model_name='match',
            name='trybonust2',
            field=models.BooleanField(default=False, verbose_name='Try Bonus'),
        ),
        migrations.AlterField(
            model_name='team',
            name='shortname',
            field=models.CharField(max_length=50, verbose_name='Short Name'),
        ),
    ]
