# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_add_division_icon_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name'),
        ),
    ]
