# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20170816_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Division', verbose_name='Division'),
        ),
    ]
